name: Angular Jasmine Tests

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Adjust as needed

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Run Jasmine tests
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless

      - name: Run Karma tests with coverage
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
