name: Test coverage

on:
  push:
    branches:
        - develop
        - main
        - release

  pull_request:
    types: [opened, edited, synchronize, reopened, converted_to_draft, ready_for_review]
    branches:
        - develop
        - main
        - release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Adjust as needed

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Run Jasmine tests
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless

      - name: Run Karma tests with coverage
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
