name: Angular Jasmine Tests

on:
  push:
    branches:
      - feature/coverage
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Adjust as needed

      - name: Install dependencies
        run: npm ci

      - name: Run Jasmine tests
        run: npm test

      - name: Run Karma tests with coverage
        run: npm test --no-watch --no-progress --watch=false --browsers=ChromeHeadless --code-coverage=true

      - name: Get coverage summary
        id: coverage
        run: |
          coverage=$(awk '/Statements/ {print $3}' coverage/web_sport_app/index.html | tr -d '%')
          echo "COVERAGE=$coverage" >> $GITHUB_ENV

      - name: Check coverage threshold
        run: |
          if (( $(echo "$COVERAGE" | awk '{print ($1 >= 60) ? "1" : "0"}') )); then
            echo "Coverage meets threshold"
          else
            echo "Coverage does not meet threshold"
            exit 1
          fi